#!/command/with-contenv sh
# Authenticate with Obsidian using the provided auth token.

echo "[obsidian-sync] Logging in to Obsidian..."
s6-setuidgid obsidian ob login

echo "[obsidian-sync] Login successful."
